### ISSUE TITLE
when migrating network

### ISSUE THREAD

**Issue by dvvvsh** [YosephKS/moralis-biconomy-metatransactions#1]
this is what I get...

yarn migrate --network binance_mainnet

sers/jonathandoe/moralis-biconomy-metatransactions/Truffle/node_modules/eth-block-tracker/src/polling.js:51
        const newErr = new Error(`PollingBlockTracker - encountered an error while attempting to update latest block:\n${err.stack}`)
                       ^
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
undefined
    at PollingBlockTracker._performSync (/Users/jonathandoe/moralis-biconomy-metatransactions/Truffle/node_modules/eth-block-tracker/src/polling.js:51:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
UnhandledRejections detected
Promise {
  <rejected> {
    code: -32603,
    message: 'Unknown Error: Unauthorized',
    data: { originalError: {} }
  }
} {
  code: -32603,
  message: 'Unknown Error: Unauthorized',
  data: { originalError: {} }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
jonathandoe@MacBook-Air Truffle %

**Comment by YosephKS** [comment]
> this is what I get...
> 
> yarn migrate --network binance_mainnet
> 
> 
> sers/jonathandoe/moralis-biconomy-metatransactions/Truffle/node_modules/eth-block-tracker/src/polling.js:51
>         const newErr = new Error(`PollingBlockTracker - encountered an error while attempting to update latest block:\n${err.stack}`)
>                        ^
> Error: PollingBlockTracker - encountered an error while attempting to update latest block:
> undefined
>     at PollingBlockTracker._performSync (/Users/jonathandoe/moralis-biconomy-metatransactions/Truffle/node_modules/eth-block-tracker/src/polling.js:51:24)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> UnhandledRejections detected
> Promise {
>   <rejected> {
>     code: -32603,
>     message: 'Unknown Error: Unauthorized',
>     data: { originalError: {} }
>   }
> } {
>   code: -32603,
>   message: 'Unknown Error: Unauthorized',
>   data: { originalError: {} }
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> jonathandoe@MacBook-Air Truffle % 
> 

Hey @dvvvsh this is not an issue at all. When deploying smart contract to the blockchain sometimes connection could be unstable, especially on the testnet, so you just need to run the same command again and it'll migrate from where you left off

In the case that your node is highly unstable, I recommend you find another RPC URL with more stable connections 🙌

Cheers~
