### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by enricobottazzi** [YosephKS/moralis-biconomy-metatransactions#2]
When trying the demo I found a wallet imported into my browser. You should fix it

**Comment by YosephKS** [comment]
> When trying the demo I found a wallet imported into my browser. You should fix it 

Hey please give me detail on the issue you found and how and where did you find it? Just finding an address in the browser doesn't pose any security risk 🙌 since public keys are not sensitive information. Also might be either it is your own wallet address or some smart contract address

**Comment by enricobottazzi** [comment]
Sure, this is the wallet address I found imported in my browser: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266. 
<img width="1407" alt="Screenshot 2022-01-14 at 15 05 02" src="https://user-images.githubusercontent.com/85900164/149536880-0185276a-10bb-4b45-a266-09051f03e5d3.png">

**Comment by YosephKS** [comment]
> Sure, this is the wallet address I found imported in my browser: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266. 
> <img width="1407" alt="Screenshot 2022-01-14 at 15 05 02" src="https://user-images.githubusercontent.com/85900164/149536880-0185276a-10bb-4b45-a266-09051f03e5d3.png">
> 
> 

It's a contract address which we'll like to interact with and implement gasless transaction on 🙌 beside if it is a wallet addresss it's in no way a security issue unless it is a private key/mnemonics.
